# Generated by Django 3.2.8 on 2021-10-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_day_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='time',
            field=models.DateField(),
        ),
    ]
