# Generated by Django 3.2.8 on 2021-10-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_day_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='name',
        ),
    ]
