# Generated by Django 3.2.8 on 2021-10-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_day_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
