# Generated by Django 3.2.8 on 2021-10-05 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='start_time',
        ),
        migrations.AddField(
            model_name='week',
            name='week',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(53)]),
        ),
        migrations.AddField(
            model_name='week',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
