# Generated by Django 3.2.8 on 2021-10-05 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211005_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(53)]),
        ),
        migrations.AlterField(
            model_name='week',
            name='year',
            field=models.IntegerField(),
        ),
    ]
