# Generated by Django 3.2.8 on 2021-10-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211005_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday')], max_length=9)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.week')),
            ],
        ),
    ]
